In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.int)
# x = torch.IntTensor([[1,2,3], [4,5,6], [7,8,9]])

print("tensor의 모양 알아보기")
print("x =\n", x)
print("x.type() =", x.type())

tensor의 모양 알아보기
x =
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
x.type() = torch.IntTensor


In [3]:
print("rank 알아보기")
print("x.shape        =", x.shape)
print("x.size()       =", x.size())
print("len(x.shape)   =", len(x.shape))
print("x.ndimension() =", x.ndimension())
print("x.ndim         =", x.ndim)

rank 알아보기
x.shape        = torch.Size([3, 3])
x.size()       = torch.Size([3, 3])
len(x.shape)   = 2
x.ndimension() = 2
x.ndim         = 2


In [14]:
print("텐서 모양 바꾸기")
x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print("x0 =\n", x0, sep="")
print("x0.shape =", x0.shape, "\n")
print("x1 =\n", x1, sep="")
print("x1.shape =", x1.shape, "\n")
print("x2 =\n", x2, sep="")
print("x2.shape =", x2.shape)

텐서 모양 바꾸기
x0 =
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
x0.shape = torch.Size([1, 3, 3]) 

x1 =
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]], dtype=torch.int32)
x1.shape = torch.Size([3, 1, 3]) 

x2 =
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]], dtype=torch.int32)
x2.shape = torch.Size([3, 3, 1])


In [11]:
x3 = torch.squeeze(torch.squeeze(x0))
print("x3 =\n", x3, sep="")
print("x3.shape =", x3.shape)

x3 =
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
x3.shape = torch.Size([3, 3])


In [16]:
x4 = x.view(9)
print("x4 =\n", x4, sep="")
print("x4.shape =", x4.shape, "\n")

x5 = x.view(1,3,3)
print("x5 =\n", x5, sep="")
print("x5.shape =", x5.shape)

x4 =
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
x4.shape = torch.Size([9]) 

x5 =
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
x5.shape = torch.Size([1, 3, 3])


In [23]:
print("행렬 연산")
x = torch.FloatTensor([[1,2], [3,4], [5,6]]) # 3 x 2
w = torch.randn(1,2, dtype=torch.float)      # (1 x 2) T
b = torch.randn(3,1, dtype=torch.float)

print("x * w + b =")
print(torch.mm(x, torch.t(w)) + b) # torch.mm(x, w.T) + b
print((x * w).sum(axis=1).view(3,1) + b)

행렬 연산
x * w + b =
tensor([[2.2450],
        [2.9820],
        [6.0972]])
tensor([[2.2450],
        [2.9820],
        [6.0972]])


In [25]:
print("기울기 계산")
w = torch.tensor(1.9, requires_grad=True)
a = w*3
l = a**2
l.backward()
print('1을 w로 미분한 값은', w.grad)

기울기 계산
1을 w로 미분한 값은 tensor(34.2000)


In [37]:
print("Linear Regression")

x = torch.FloatTensor([[1,2], [3,2], [3,7], [1,1], [1,0]])
y = torch.FloatTensor([[4], [8], [23], [1], [-2]])

W = torch.zeros(2,1)
b = torch.zeros(1)

lr = 0.01

for epoch in range(10000):
  W.requires_grad_(True)
  b.requires_grad_(True)

  h = torch.mm(x, W) + b
  cost = torch.mean((h - y) ** 2)

  cost.backward()
  with torch.no_grad():
    W = W - lr * W.grad
    b = b - lr * b.grad

    if epoch%1000 == 0:
      print(f"W: {W}, b: {b}, cost: {cost}")

Linear Regression
W: tensor([[0.3840],
        [0.7440]]), b: tensor([0.1360]), cost: 122.80000305175781
W: tensor([[1.9230],
        [3.0139]]), b: tensor([-3.8739]), cost: 0.003685731440782547
W: tensor([[1.9972],
        [3.0005]]), b: tensor([-3.9955]), cost: 4.738011284644017e-06
W: tensor([[1.9999],
        [3.0000]]), b: tensor([-3.9998]), cost: 6.3765810409677215e-09
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10
W: tensor([[2.0000],
        [3.0000]]), b: tensor([-4.0000]), cost: 2.817159838741645e-10


In [38]:
x_test = torch.tensor([[5,10]], dtype=torch.float)
test_result = torch.mm(x_test, W) + b
print(test_result)

tensor([[36.0000]])


In [44]:
from sklearn.linear_model import LinearRegression

print("Scikit-learn")

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression()
model.fit(x,y)

print(model.coef_, model.intercept_)

print("y 값 예측하기")
print(model.predict([[5,10]]))

Scikit-learn
[[2. 3.]] [-4.]
y 값 예측하기
[[36.]]
